/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "kintone UI Component · Be a smart kintone developer.",
  "headTags": [
    {
      "tagName": "meta",
      "attributes": {
        "name": "description",
        "content": "Be a smart kintone developer"
      }
    }
  ],
  "tagline": "It will support your UI customization project.",
  "url": "https://kintone-ui-component.netlify.app",
  "baseUrl": "/ja/",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/kuc_box_yellow.png",
  "organizationName": "kintone-labs",
  "projectName": "kintone-ui-component",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "ja"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "scripts": [
    "https://unpkg.com/kintone-ui-component/umd/kuc.min.js"
  ],
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "/Users/a001860/Desktop/my/docusaurus/docusaurus/sidebars.js",
          "lastVersion": "1.11.0"
        },
        "theme": {
          "customCss": [
            "/Users/a001860/Desktop/my/docusaurus/docusaurus/src/css/custom.css",
            "/Users/a001860/Desktop/my/docusaurus/docusaurus/src/css/kuc-custom.css"
          ]
        },
        "googleTagManager": {
          "containerId": "GTM-5N49D3"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "",
      "logo": {
        "alt": "kintone UI Component",
        "src": "img/kuc_logo_white.png"
      },
      "items": [
        {
          "type": "docsVersion",
          "position": "left",
          "to": "/versions",
          "className": "versions"
        },
        {
          "type": "doc",
          "docId": "getting-started/quick-start",
          "position": "right",
          "label": "Documentation"
        },
        {
          "type": "doc",
          "docId": "releases/release-notes",
          "position": "right",
          "label": "Releases"
        },
        {
          "href": "https://github.com/kintone-labs/kintone-ui-component",
          "label": "GitHub",
          "position": "right"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "type": "search",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Quick Start",
              "to": "/docs/getting-started/quick-start"
            },
            {
              "label": "Components",
              "to": "/docs/components/desktop/attachment"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub issue",
              "href": "https://github.com/kintone-labs/kintone-ui-component/issues"
            }
          ]
        },
        {
          "title": "Other",
          "items": [
            {
              "label": "Privacy Policy",
              "href": "https://cybozu.co.jp/privacy/"
            },
            {
              "label": "License",
              "href": "https://github.com/kintone-labs/kintone-ui-component/blob/master/docs/document/LICENSE"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 Cybozu Inc."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "algolia": {
      "appId": "QJ2QB6FCE5",
      "apiKey": "636c5f8d218f77cc2f87c81fbd95a9b8",
      "indexName": "kuc-usaurus-v2",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
